<?php
// This file is part of Moodle - https://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <https://www.gnu.org/licenses/>.

/**
 * English strings for plagiarism_lucide.
 *
 * @package    plagiarism_lucide
 * @copyright  2026 Lucide
 * @license    https://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */

defined('MOODLE_INTERNAL') || die();

$string['analysedon'] = 'Analysed on';
$string['analysedtext'] = 'Analysed text';
$string['analysenow'] = 'Analyse';
$string['apikey'] = 'Lucide API key';
$string['apikey_help'] = 'Create a key in your Lucide account, under API, and tick the three rights: run analyses, import files, delete analyses. The key is shown once only. It is stored in the Moodle database like other plugin settings: anyone with access to the database or its backups can read it.';
$string['apikeyrequired'] = 'Enter a Lucide API key.';
$string['assignment'] = 'Assignment';
$string['authblocked'] = 'Sending to Lucide is stopped: the key was refused ({$a}). Check the key and the Lucide subscription, then run the connection test.';
$string['badge_ai'] = 'Likely AI';
$string['badge_human'] = 'Likely human';
$string['badge_maybe'] = 'Uncertain';
$string['badge_unknown'] = 'Analysed';
$string['badge_veryai'] = 'AI detected';
$string['badge_veryhuman'] = 'Human';
$string['connection'] = 'Connection';
$string['connectionfailed'] = 'Lucide refused the connection: {$a->code}. {$a->message}';
$string['connectionok'] = 'Connected. Model {$a->model}, plan {$a->tier}, up to {$a->maxwords} words per text. Credits available: {$a->available} (reserved: {$a->reserved}).';
$string['coverage_long'] = '{$a} % of the text is highlighted as AI-like.';
$string['coverage_short'] = '{$a} % highlighted';
$string['creditsused'] = 'Credits used';
$string['cronlate'] = 'The Lucide task has not run for more than 10 minutes. Check that the Moodle cron runs every minute.';
$string['defaultenabled'] = 'On by default for new assignments';
$string['defaultenabled_help'] = 'Teachers can still switch Lucide off in each assignment.';
$string['deleteremote'] = 'Erase the copy at Lucide once the report is in Moodle';
$string['deleteremote_help'] = 'Recommended. As soon as the report is stored in Moodle, the plugin asks Lucide to erase the text and its result. Without this option, Lucide keeps them 7 days.';
$string['deleterightmissing'] = 'The key does not allow erasing analyses at Lucide: copies stay there 7 days. Create a key with the three rights (run analyses, import files, delete analyses) and paste it here.';
$string['disclosure'] = 'Notice shown to students';
$string['disclosure_default'] = 'Your work will be analysed by Lucide, a tool that detects text generated by artificial intelligence. Only your teachers see the result. Lucide erases your text from its servers as soon as the analysis is done.';
$string['disclosure_help'] = 'Shown on the submission page of assignments where Lucide is on. Leave empty to use the default text.';
$string['educationalnotice'] = 'This analysis is a clue to examine together with the work and its context. On its own, it is not proof of cheating.';
$string['enabled'] = 'Enable Lucide';
$string['enabled_help'] = 'Also check that plagiarism plugins are enabled for the site (Advanced features).';
$string['enableforactivity'] = 'Analyse submissions with Lucide';
$string['enableforactivity_help'] = 'Each handed-in text and each PDF, Word (docx) or text file is analysed in the background. The teacher sees the verdict next to the work. Cost: 1 Lucide credit per 100 words.';
$string['error_credit_budget_exceeded'] = 'over the credit limit';
$string['error_credit_replenishment_pending'] = 'credits being topped up';
$string['error_engine_unavailable'] = 'Lucide unavailable';
$string['error_extracted_text_too_large'] = 'too long';
$string['error_file_rejected'] = 'file refused';
$string['error_insufficient_credits'] = 'not enough credits';
$string['error_no_extractable_text'] = 'no readable text (scanned document?)';
$string['error_other'] = 'not analysed';
$string['error_payload_too_large'] = 'file over 10 MB';
$string['error_report_unavailable'] = 'report unavailable';
$string['error_text_too_long'] = 'too long';
$string['error_text_too_short'] = 'too short to analyse';
$string['error_timeout'] = 'Lucide could not be reached';
$string['error_unsupported_format'] = 'format not supported';
$string['formheader'] = 'Lucide — AI-generated text detection';
$string['health_analysing'] = 'Being analysed';
$string['health_blocked'] = 'Waiting for credits';
$string['health_completed'] = 'Reports available';
$string['health_extracting'] = 'Files being read';
$string['health_failed'] = 'Not analysable';
$string['health_lastcontact'] = 'Last exchange with Lucide';
$string['health_lastcron'] = 'Last run of the task';
$string['health_queued'] = 'Waiting to be sent';
$string['health_remotedeletes'] = 'Erasures at Lucide to confirm';
$string['health_unsupported'] = 'Unsupported formats';
$string['keptuntil'] = 'Report kept until';
$string['legend_ai'] = 'Reads as AI';
$string['legend_ai_medium'] = 'Reads as AI, less certain';
$string['lowconfidence'] = 'Short text: the verdict is less reliable.';
$string['lucide:enable'] = 'Switch Lucide on or off in an activity';
$string['lucide:requestscan'] = 'Ask Lucide to analyse a submission';
$string['lucide:viewreport'] = 'See Lucide reports';
$string['maxcredits'] = 'Maximum credits per text';
$string['maxcredits_help'] = 'A text that would cost more is not analysed. 1 credit per 100 words: 200 credits cover 20,000 words.';
$string['maxcreditsinvalid'] = 'Enter a number of credits of at least 1.';
$string['modelinfo'] = 'Model {$a->model}, scoring policy of {$a->policy}.';
$string['nosegments_diffuse'] = 'The whole text reads as AI, with no single passage standing out.';
$string['nosegments_human_verdict'] = 'No passage is highlighted when the verdict is human.';
$string['nosegments_unavailable'] = 'Passage detail is not available for this text.';
$string['notenabled'] = 'Lucide is not enabled for this activity.';
$string['plagiarismdisabled'] = 'Plagiarism plugins are disabled for the site. Enable them in <a href="{$a}">Advanced features</a>.';
$string['pluginname'] = 'Lucide';
$string['privacy:export'] = 'Lucide';
$string['privacy:metadata:lucide'] = 'To detect AI-generated text, the plugin sends the text of submissions to Lucide. No name, email address or course title is sent; a text may still contain personal data written by its author.';
$string['privacy:metadata:lucide:content'] = 'Online text of the submission.';
$string['privacy:metadata:lucide:file'] = 'Submitted file (PDF, Word or text), sent under a neutral name.';
$string['privacy:metadata:plagiarism_lucide_src'] = 'Analyses of submissions and their reports.';
$string['privacy:metadata:plagiarism_lucide_src:filename'] = 'Name of the analysed file, kept in Moodle only.';
$string['privacy:metadata:plagiarism_lucide_src:report'] = 'Analysed text and highlighted passages.';
$string['privacy:metadata:plagiarism_lucide_src:score'] = 'Decision score of the model.';
$string['privacy:metadata:plagiarism_lucide_src:submissionid'] = 'Analysed submission.';
$string['privacy:metadata:plagiarism_lucide_src:timecreated'] = 'Date of the request.';
$string['privacy:metadata:plagiarism_lucide_src:userid'] = 'Author of the submission.';
$string['privacy:metadata:plagiarism_lucide_src:verdict'] = 'Verdict of the analysis.';
$string['queuehealth'] = 'Activity';
$string['reportretention'] = 'Keep reports in Moodle for';
$string['reportretention_help'] = 'After this delay the report is erased from Moodle. Deleting the submission, the activity or the user erases it at once.';
$string['reporttitle'] = 'Lucide AI analysis';
$string['scanexisting'] = 'Also analyse the {$a} submissions already handed in';
$string['scanexisting_help'] = 'Switching Lucide on does not send work handed in earlier. Tick this box to analyse it too. Each text uses credits.';
$string['scanrequested'] = 'Analysis requested. The result will appear within a few minutes.';
$string['settingsintro'] = 'Lucide detects text generated by artificial intelligence in French-language work. Submissions are analysed in the background; a Lucide outage never prevents a student from handing in.';
$string['source'] = 'Source';
$string['source_file'] = 'File: {$a}';
$string['source_file_hidden'] = 'Submitted file (anonymous marking)';
$string['source_onlinetext'] = 'Online text';
$string['status_blocked'] = 'Waiting for credits';
$string['status_expired'] = 'Report expired';
$string['status_failed'] = 'Not analysed';
$string['status_none'] = 'Not analysed yet';
$string['status_pending'] = 'Analysis in progress';
$string['task_cleanup'] = 'Lucide: purge expired reports';
$string['task_process_queue'] = 'Lucide: send submissions and collect reports';
$string['testconnection'] = 'Test the connection';
$string['verdict'] = 'Verdict';
$string['verdict_ai'] = 'Probably written by AI';
$string['verdict_human'] = 'Probably human';
$string['verdict_maybe'] = 'Maybe written by AI';
$string['verdict_unknown'] = 'Analysed';
$string['verdict_veryai'] = 'Very probably written by AI';
$string['verdict_veryhuman'] = 'Very probably human';
$string['viewreport'] = 'See the report';
$string['wordcount'] = 'Length analysed';
$string['words'] = '{$a} words';
